env:
  global:
    - CC_TEST_REPORTER_ID=e829bf507687e499cd7571473ac8b334b457e4fb88990c906123520b9fc5d3f9

language:
  - php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

node_js:
  - 6

before_install:
  - ./tests/server/start_server.sh
  - sleep 5

install:
  - composer install

addons:
  code_climate:
    repo_token: $CC_TEST_REPORTER_ID

script:
  - vendor/bin/phpunit
  - vendor/bin/test-reporter
